
# This file defines metadata about Supabase Edge Functions.
# This file is required to deploy with the Supabase CLI.
#
# For more information, see:
# https://supabase.com/docs/guides/functions/quickstart#supabase-config

project_id = "igqzsdtjvovfnctboqwc"

[functions.manage-collection-points]
verify_jwt = true
